name: Delete Merged Branch
on:
  pull_request:
    types:
      - closed 

jobs:
  delete_merged_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch if merged
        uses: github-actions/delete-merged-branch@v4
        with:
          github_token: ${{ secrets.TOKEN }}
